### ISSUE TITLE
Input format for dcase_util.data.DecisionEncoder Class - Doubt

### ISSUE THREAD

**Issue by n33lkanth** [TUT-ARG/DCASE2017-baseline-system#39]
Hi @toni-heittola ,
I was going through the [dcase_util package doc](https://dcase-repo.github.io/dcase_util/tutorial_data.html#decision-encoding) and under _Decision encoding_ section it says: '_DecisionEncoder class (dcase_util.data.DecisionEncoder) can used to process binary 2D data matrix **(class, time)** with frame wise activity_'. In my case (the project I am working on) the prediction output I am getting is **(time, class)** format. So, I was thinking if this is Ok to pass 2D matrix (to dcase_util.data.DecisionEncoder) as **(time, class)** format or not as I am getting very poor score both from segment based and event based evaluation metrices (ER & F1).

Best Regards

**Comment by toni-heittola** [comment]
The correct place for this issue is at the `dcase_util` repository > https://github.com/DCASE-REPO/dcase_util

You just need to convert your system output with one-hot encoding into a 2D data matrix. This can be easily implemented (you know the number of frames and classes, so then is it just a matter of correct indexing and placing ones in zero initialized matrix), or use ready tools from the scikit-learn package > https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.OneHotEncoder.html
